config/routes.rb
# frozen_string_literal: true

Reservations::Application.routes.draw do
  root to: 'catalog#index'

  # routes for Devise
  devise_scope :user do
    devise_for :users
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  ## Concerns
  concern :deactivatable do
    member do
      put :deactivate
      put :activate
    end
  end

  concern :calendarable do
    member { get :calendar }
  end

  resources :documents,
            :requirements

  resources :equipment_items, concerns: %i[deactivatable calendarable]

  resources :announcements, except: [:show]

  resources :categories, concerns: %i[deactivatable calendarable] do
    resources :equipment_models, concern: :calendarable
  end

  resources :equipment_models, concerns: %i[deactivatable calendarable] do
    collection do
      put 'update_catalog_cart'
      delete 'empty_cart'
    end
    resources :equipment_items, concerns: :calendarable
  end

  get 'equipment_objects', to: redirect('equipment_items')
  get 'equipment_objects/:id', to: redirect('equipment_items/%<id>')

  get '/import_users/import', to: 'import_users#import_page',
                              as: :csv_import_page
  post '/import_users/imported', to: 'import_users#import',
                                 as: :csv_imported

  get '/import_equipment/import', to: 'import_equipment#import_page',
                                  as: :equip_import_page
  post '/import_equipment/imported', to: 'import_equipment#import',
                                     as: :equip_imported

  resources :users, concerns: :calendarable do
    collection do
      post :find
      post :quick_new
      post :quick_create
    end
    member do
      put :ban
      put :unban
      delete :empty_cart
    end
    get :autocomplete_user_last_name, on: :collection
  end

  get '/catalog/search', to: 'catalog#search', as: :catalog_search
  get '/markdown_help', to: 'application#markdown_help', as: :markdown_help

  resources :reservations do
    member do
      get :send_receipt
      put :renew
      put :archive
    end
  end

  # reservations views
  get '/reservations/manage/:user_id', to: 'reservations#manage',
                                       as: :manage_reservations_for_user
  get '/reservations/current/:user_id', to: 'reservations#current',
                                        as: :current_reservations_for_user

  get '/reservations/review/:id', to: 'reservations#review',
                                  as: :review_request
  put '/reservations/approve/:id', to: 'reservations#approve_request',
                                   as: :approve_request
  put '/reservations/deny/:id', to: 'reservations#deny_request',
                                as: :deny_request

  # reservation checkout / check-in actions
  put '/reservations/checkout/:user_id', to: 'reservations#checkout',
                                         as: :checkout
  put '/reservations/check-in/:user_id', to: 'reservations#checkin',
                                         as: :checkin
  get '/blackouts/flash_message', to: 'blackouts#flash_message',
                                  as: :flash_message
  get '/blackouts/new_recurring', to: 'blackouts#new_recurring',
                                  as: :new_recurring_blackout

  put '/reservation/update_index_dates', to: 'reservations#update_index_dates',
                                         as: :update_index_dates
  put '/reservation/view_all_dates', to: 'reservations#view_all_dates',
                                     as: :view_all_dates

  resources :blackouts do
    collection do
      post :create_recurring
    end
    member do
      get :flash_message
      delete :destroy_recurring
    end
  end

  put '/catalog/update_view', to: 'catalog#update_user_per_cat_page',
                              as: :update_user_per_cat_page
  get '/catalog', to: 'catalog#index', as: :catalog
  put '/add_to_cart/:id', to: 'catalog#add_to_cart', as: :add_to_cart
  put '/remove_from_cart/:id', to: 'catalog#remove_from_cart',
                               as: :remove_from_cart
  put '/catalog/edit_cart_item/:id', to: 'catalog#edit_cart_item',
                                     as: :edit_cart_item
  post '/catalog/submit_cart_updates_form/:id',
       to: 'catalog#submit_cart_updates_form', as: :submit_cart_updates
  put '/catalog/reload_catalog_cart', to: 'catalog#reload_catalog_cart',
                                      as: :reload_catalog_cart
  put '/catalog/change_reservation_dates',
      to: 'catalog#change_reservation_dates',
      as: :change_reservations_dates
  delete '/catalog/empty_cart', to: 'catalog#empty_cart',
                                as: :catalog_empty_cart

  get '/reports/index', to: 'reports#index', as: :reports
  get '/reports/subreport/:class/:id', to: 'reports#subreport', as: :subreport
  put '/reports/update', to: 'reports#update_dates', as: :update_dates

  get '/terms_of_service', to: 'application#terms_of_service', as: :tos

  # yes, both of these are needed to override rails defaults of
  # /controller/:id/edit
  get '/app_configs/', to: 'app_configs#edit', as: :edit_app_configs # match
  resources :app_configs, only: %i[update] do
    collection do
      put :run_hourly_tasks
      put :run_daily_tasks
    end
  end

  get '/new_admin_user', to: 'application_setup#new_admin_user',
                         as: :new_admin_user
  post '/create_admin_user', to: 'application_setup#create_admin_user',
                             as: :create_admin_user
  resources :application_setup, only: %i[new_admin_user create_admin_user]

  get '/new_app_configs', to: 'application_setup#new_app_configs',
                          as: :new_app_configs
  post '/create_app_configs', to: 'application_setup#create_app_configs',
                              as: :create_app_configs
  put '/reload_catalog_cart', to: 'application#reload_catalog_cart',
                              as: :reload_cart
  delete '/empty_cart', to: 'application#empty_cart', as: :empty_cart

  get 'contact', to: 'contact#new', as: 'contact_us'
  post 'contact', to: 'contact#create', as: 'contact_submitted'

  get 'announcements/:id/hide',
      to: 'announcements#hide',
      as: 'hide_announcement'

  get 'status', to: 'status#index'

  get 'status/index'

  # this is a fix for running letter opener inside vagrant
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/blackout.rb
# frozen_string_literal: true

class Blackout < ApplicationRecord
  attr_accessor :days # needed for days of the week checkboxes in new_recurring

  validates :notice,
            :start_date,
            :blackout_type,
            :end_date, presence: true

  validate :validate_end_date_before_start_date
  # this only matters if a user tries to inject into params because the
  # datepicker doesn't allow form submission of invalid dates

  scope :active, ->() { where('end_date >= ?', Time.zone.today) }
  scope :for_date, lambda { |date|
    where('end_date >= ? and start_date <= ?', date, date)
  }
  scope :hard, ->() { where(blackout_type: 'hard') }
  scope :soft, ->() { where(blackout_type: 'soft') }

  def self.get_notices_for_date(date, type = :all)
    # get a string of all notices for a given date
    # default to all blackouts
    blackouts = if type == :soft
                  Blackout.soft.for_date(date)
                elsif type == :hard
                  Blackout.hard.for_date(date)
                else
                  Blackout.for_date(date)
                end
    messages = []
    blackouts.for_date(date).each do |b|
      messages << b.notice
    end
    messages.to_sentence
  end

  def self.create_blackout_set(params_hash, days) # rubocop:disable all
    # generate a unique id for this blackout date set, make sure that nil
    # reads as 0 for the first blackout
    last_blackout = Blackout.last
    params_hash[:set_id] = last_blackout ? (last_blackout.id.to_i + 1) : 0
    date_range =
      params_hash[:start_date].to_date..params_hash[:end_date].to_date

    # initialize arrays for query dates and blackout objects
    res_dates = []
    blackouts_tmp = []
    date_range.each do |date|
      # because it's passed as a string
      next unless days.include?(date.wday.to_s)
      @blackout = Blackout.new(params_hash)
      @blackout.start_date = date
      @blackout.end_date = date
      # save dates for conflict checking and blackout objects
      res_dates << DateTime.parse(date.to_s) # rubocop:disable TimeZone
      blackouts_tmp << @blackout
    end
    # check for conflicts
    res = Reservations::AffectedByRecurringBlackoutQuery.call(res_dates)
    if res.empty?
      # try to save all of the blackouts
      successful_save = nil
      blackouts_tmp.each do |blackout|
        successful_save = blackout.save
      end
    else
      # if conflicts exist, generate appropriate flash message
      msg = 'The following reservation(s) will be unable to be returned: '
      res.each do |res2|
        msg += "#{res2.md_link}, "
      end
      return msg[0, msg.length - 2] + '. Please update their due dates and '\
        'try again.'
    end

    invalid_dates_msg = 'The combination of days and dates chosen did not '\
      'produce any valid blackout dates. Please change your selection and try '\
      'again.'
    return invalid_dates_msg unless successful_save
  end

  private

  def validate_end_date_before_start_date
    return unless end_date && start_date && (end_date < start_date)
    errors.add(:end_date, 'Start date must be before end date.')
  end

  # end private methods
end

app/controllers/blackouts_controller.rb
# frozen_string_literal: true

class BlackoutsController < ApplicationController
  load_and_authorize_resource
  before_action :set_current_blackout,
                only: %i[edit show update destroy destroy_recurring]

  # ---------- before filter methods ------------ #

  def set_current_blackout
    @blackout = Blackout.find(params[:id])
  end

  # ---------- end before filter methods ------------ #

  def index
    @blackouts = Blackout.all
  end

  def show
    return if @blackout.set_id.nil?
    @blackout_set = Blackout.where('set_id = ?', @blackout.set_id)
  end

  def new
    @blackout = Blackout.new(start_date: Time.zone.today,
                             end_date: Time.zone.today + 1.day)
  end

  def new_recurring
    @blackout = Blackout.new(start_date: Time.zone.today,
                             end_date: Time.zone.today + 1.day)
  end

  def edit; end

  def create_recurring
    # called when a recurring blackout is needed
    # this class method will parse the params hash
    # and create separate blackouts on each appropriate date

    @blackout = Blackout.new(blackout_params) # for the form if there are errors

    if params[:blackout][:days].reject(&:blank?).empty?
      flash[:error] = 'You must select at least one day of the week for any '\
      'recurring blackouts to be created.'
      render('new_recurring') && return
    end

    render('new_recurring') && return unless @blackout.valid?

    p = blackout_params
    p[:created_by] = current_user.id

    # method will return an error message if save is not successful
    flash[:error] = Blackout.create_blackout_set(p, params[:blackout][:days])
    # if there is an error, show it and redirect :back
    if flash[:error]
      render 'new_recurring'
    else
      redirect_to blackouts_path, notice: 'Blackouts were successfully created.'
    end
  end

  def create
    # create a non-recurring blackout
    p = blackout_params
    p[:created_by] = current_user.id
    @blackout = Blackout.new(p)

    # check for conflicts
    res = Reservation.affected_by_blackout(@blackout).active

    # save and exit
    if res.empty? && @blackout.save
      redirect_to @blackout, notice: 'Blackout was successfully created.'
    else
      if res.empty?
        msg = 'Oops, something went wrong. Please try again.'
      else
        msg = 'The following reservation(s) will be unable to be returned: '
        res.each do |res2|
          msg += "#{res2.md_link}, "
        end
        msg = msg[0, msg.length - 2]\
            + '. Please update their due dates and try again.'
      end

      flash[:error] = msg
      render action: 'new'
    end
  end

  def update
    @blackout.set_id = nil
    updater = BlackoutUpdater.new(blackout: @blackout,
                                  params: blackout_params)
    result = updater.update

    if result[:error]
      flash[:error] = result[:error]
      render action: 'edit'
    else
      redirect_to @blackout, notice: result[:result]
    end
  end

  def destroy
    @blackout.destroy
    redirect_to blackouts_url
  end

  def destroy_recurring
    blackout_set = Blackout.where('set_id = ?', @blackout.set_id)
    blackout_set.each(&:destroy)
    flash[:notice] = 'All blackouts in the set were successfully destroyed.'
    redirect_to(blackouts_path) && return
  end

  private

  def blackout_params
    params.require(:blackout)
          .permit(:start_date, :end_date, :notice, :blackout_type, :created_by,
                  :set_id)
  end
end

app/views/blackouts/_blackout_array.html.erb
<%# Blackout.all.collect{|bo| [bo.start_date.strftime("%Y,%m,%d"), bo.end_date.strftime("%Y,%m,%d")]} %>

app/views/blackouts/_form.html.erb
  <%= f.input :blackout_type, label: 'Blackout Type', collection: [['Blackout',"hard"],['Notice Only',"soft"]] %>
  <div class="form-group">
    <%= label_tag :start_date, 'Start of Blackout', class: 'col-sm-2 control-label' %>
    <div class="col-sm-7">
      <%= f.text_field :start_date, class: 'date_start form-control', :value => @blackout[:start_date].strftime('%m/%d/%Y') %>
      <%= f.input :start_date, as: :hidden, input_html: {id: 'date_start_alt'} %>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :end_date, 'End of Blackout', class: 'col-sm-2 control-label' %>
    <div class="col-sm-7">
      <%= f.text_field :end_date, :class => 'date_end form-control', :value => @blackout[:end_date].strftime('%m/%d/%Y') %>
      <%= f.input :end_date, as: :hidden, input_html: {id: 'date_end_alt'} %>
    </div>
  </div>

  <%= f.input :notice, hint: 'This message will be displayed to users if they attempt to make a reservation on a blackout date' %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.button :submit, cancel: blackouts_path %>
    </div>
  </div>

app/views/blackouts/_table.html.erb
<table class="datatable-wide table table-stripped table-bordered">
  <thead>
    <tr>
      <% if request.path == blackouts_path %>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Recurring?</th>
      <% elsif params[:action] == "show" %>
        <th>Date</th>
      <% end %>
      <th>Notice</th>
      <th>Last Edited By</th> <%# This field cannot be manually updated. %>
      <th>Type</th>
      <% unless params[:action] == "show" %>
        <th class="no_sort"></th> <%# show %>
      <% end %>
      <th class="no_sort"></th> <%# edit %>
      <th class="no_sort">
        <% if params[:action] == "show" %>
          <%= link_to "Delete all", destroy_recurring_blackout_path, :data => {:confirm => 'Are you sure?' }, :method => :delete, :class => 'btn btn-danger' %>
        <% end %>
      </th> <%# destroy %>
    </tr>
  </thead>
  <tbody>
    <% blackouts.each do |blackout| %>
      <tr>
        <td>
          <% if params[:action] == "show" %>
            <%= link_to blackout[:start_date].strftime('%m/%d/%Y'), blackout %>
          <% else %>
            <%= blackout[:start_date].strftime('%m/%d/%Y') %>
          <% end %>
        </td>
        <% if request.path == blackouts_path %>
          <td><%= blackout[:end_date].strftime('%m/%d/%Y') %></td>
          <td>
            <% if blackout.set_id.nil? %>
              No
            <% else %>
              Yes
            <% end %>
          </td>
        <% end %>
        <td><%= blackout.notice %></td>
        <td><%= User.find((blackout[:created_by])).name %></td>
        <td><%= blackout[:blackout_type] == "hard" ? "Hard Blackout" : "Notice Only" %></td>
        <% unless params[:action] == "show" %>
          <td><%= link_to 'Show', blackout, class: 'btn btn-default' %></td>
        <% end %>
        <td><%= link_to 'Edit', edit_blackout_path(blackout), class: 'btn btn-default' %></td>
        <td><%= link_to 'Delete', blackout, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/blackouts/edit.html.erb
<% title 'Edit Blackout' %>

<%= simple_form_for @blackout, html: { class: 'form-horizontal' } do |f| %>
  <%= f.error_notification %>
  <%= render partial: 'form', locals: { f: f } %>
<% end %>

app/views/blackouts/index.html.erb
<% title "Blackout Dates" %>

<p class="lead">
  If a user tries to create a reservation for any of the equipment models listed
  below with a start date or end date within
  the "Blackout" period, then they will be presented with a notice (set by
  the admin) stating the exceptional circumstances for that date (e.g. 'Please
  note that our offices will only be open from 2:36 AM to 2:37 AM on this date
  in observance of Arbitrary Day.'). The admin can also set that no reservation
  can be created if its start or end
  date falls within the Blackout period. Expired blackouts will be automatically
  deleted after a certain period of time, specified in the application settings.
</p>
<p>
  <%= link_to 'New Blackout'.titleize, new_blackout_path, class: 'btn btn-primary' %>
  <%= link_to 'New Recurring Blackout'.titleize, new_recurring_blackout_path, :class => 'btn btn-primary' %>
</p>
<hr />

<% unless @blackouts.empty? %>
  <%= render :partial => 'table', :locals => {:blackouts => @blackouts} %>
  <br />
<% else %>
  <h3>No black-out dates found.</h3>
<% end %>

app/views/blackouts/new.html.erb
<% title 'New Blackout' %>

  <%= simple_form_for @blackout, html: { class: 'form-horizontal' } do |f| %>
    <%= f.error_notification %>
    <%= render partial: 'form', locals: { f: f } %>
  <% end %>

app/views/blackouts/new_recurring.html.erb
<% title 'New Recurring Blackout' %>

<%= simple_form_for @blackout, url: {controller: 'blackouts', action: 'create_recurring' },
html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f| %>
  <%= f.error_notification %>
  <%= hidden_field_tag 'recurring', true %>
  <%= f.input :days, collection: days_of_the_week_short_with_index,
    value_method: :first, label_method: :last, as: :check_boxes,
    item_wrapper_class: 'inline', required: true %>
  <%= render partial: 'form', locals: {f: f} %>
<% end %>

app/views/blackouts/show.html.erb
<% title "#{@blackout.blackout_type.capitalize} Blackout" %>
<p>
  <b>Start date:</b>
  <%= @blackout.start_date.strftime('%m/%d/%Y') %>
</p>

<p>
  <b>End date:</b>
  <%= @blackout.end_date.strftime('%m/%d/%Y') %>
</p>

<p>
  <b>Notice:</b>
  <%= @blackout.notice %>
</p>

<p>
  <b>Last Edited by:</b>
  <%= User.find(@blackout.created_by).name %>
</p>

<p>
  <b>Type:</b>
  <%= @blackout[:blackout_type] == "hard" ? "Hard Blackout" : "Notice Only" %>
</p>

<% unless @blackout.set_id.nil? or (@blackout_set.size == 1) %>
  <%= link_to 'Edit just this blackout', edit_blackout_path(@blackout), :class => 'btn btn-default' %>
  <%= link_to 'View all blackout dates', blackouts_path, :class => 'btn btn-default' %>
  <hr />
  <p>
    <h3>All Blackouts in this set</h3>
  </p>
  <%= render :partial => 'table', :locals => {:blackouts => @blackout_set} %>
<% else %>
  <%= link_to 'Edit', edit_blackout_path(@blackout), :class => 'btn btn-default' %>
  <%= link_to 'View all blackout dates', blackouts_path, :class => 'btn btn-default' %>
  <%= link_to 'Delete', @blackout, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger' %>
<% end %>