config/routes.rb
# frozen_string_literal: true

Reservations::Application.routes.draw do
  root to: 'catalog#index'

  # routes for Devise
  devise_scope :user do
    devise_for :users
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  ## Concerns
  concern :deactivatable do
    member do
      put :deactivate
      put :activate
    end
  end

  concern :calendarable do
    member { get :calendar }
  end

  resources :documents,
            :requirements

  resources :equipment_items, concerns: %i[deactivatable calendarable]

  resources :announcements, except: [:show]

  resources :categories, concerns: %i[deactivatable calendarable] do
    resources :equipment_models, concern: :calendarable
  end

  resources :equipment_models, concerns: %i[deactivatable calendarable] do
    collection do
      put 'update_catalog_cart'
      delete 'empty_cart'
    end
    resources :equipment_items, concerns: :calendarable
  end

  get 'equipment_objects', to: redirect('equipment_items')
  get 'equipment_objects/:id', to: redirect('equipment_items/%<id>')

  get '/import_users/import', to: 'import_users#import_page',
                              as: :csv_import_page
  post '/import_users/imported', to: 'import_users#import',
                                 as: :csv_imported

  get '/import_equipment/import', to: 'import_equipment#import_page',
                                  as: :equip_import_page
  post '/import_equipment/imported', to: 'import_equipment#import',
                                     as: :equip_imported

  resources :users, concerns: :calendarable do
    collection do
      post :find
      post :quick_new
      post :quick_create
    end
    member do
      put :ban
      put :unban
      delete :empty_cart
    end
    get :autocomplete_user_last_name, on: :collection
  end

  get '/catalog/search', to: 'catalog#search', as: :catalog_search
  get '/markdown_help', to: 'application#markdown_help', as: :markdown_help

  resources :reservations do
    member do
      get :send_receipt
      put :renew
      put :archive
    end
  end

  # reservations views
  get '/reservations/manage/:user_id', to: 'reservations#manage',
                                       as: :manage_reservations_for_user
  get '/reservations/current/:user_id', to: 'reservations#current',
                                        as: :current_reservations_for_user

  get '/reservations/review/:id', to: 'reservations#review',
                                  as: :review_request
  put '/reservations/approve/:id', to: 'reservations#approve_request',
                                   as: :approve_request
  put '/reservations/deny/:id', to: 'reservations#deny_request',
                                as: :deny_request

  # reservation checkout / check-in actions
  put '/reservations/checkout/:user_id', to: 'reservations#checkout',
                                         as: :checkout
  put '/reservations/check-in/:user_id', to: 'reservations#checkin',
                                         as: :checkin
  get '/blackouts/flash_message', to: 'blackouts#flash_message',
                                  as: :flash_message
  get '/blackouts/new_recurring', to: 'blackouts#new_recurring',
                                  as: :new_recurring_blackout

  put '/reservation/update_index_dates', to: 'reservations#update_index_dates',
                                         as: :update_index_dates
  put '/reservation/view_all_dates', to: 'reservations#view_all_dates',
                                     as: :view_all_dates

  resources :blackouts do
    collection do
      post :create_recurring
    end
    member do
      get :flash_message
      delete :destroy_recurring
    end
  end

  put '/catalog/update_view', to: 'catalog#update_user_per_cat_page',
                              as: :update_user_per_cat_page
  get '/catalog', to: 'catalog#index', as: :catalog
  put '/add_to_cart/:id', to: 'catalog#add_to_cart', as: :add_to_cart
  put '/remove_from_cart/:id', to: 'catalog#remove_from_cart',
                               as: :remove_from_cart
  put '/catalog/edit_cart_item/:id', to: 'catalog#edit_cart_item',
                                     as: :edit_cart_item
  post '/catalog/submit_cart_updates_form/:id',
       to: 'catalog#submit_cart_updates_form', as: :submit_cart_updates
  put '/catalog/reload_catalog_cart', to: 'catalog#reload_catalog_cart',
                                      as: :reload_catalog_cart
  put '/catalog/change_reservation_dates',
      to: 'catalog#change_reservation_dates',
      as: :change_reservations_dates
  delete '/catalog/empty_cart', to: 'catalog#empty_cart',
                                as: :catalog_empty_cart

  get '/reports/index', to: 'reports#index', as: :reports
  get '/reports/subreport/:class/:id', to: 'reports#subreport', as: :subreport
  put '/reports/update', to: 'reports#update_dates', as: :update_dates

  get '/terms_of_service', to: 'application#terms_of_service', as: :tos

  # yes, both of these are needed to override rails defaults of
  # /controller/:id/edit
  get '/app_configs/', to: 'app_configs#edit', as: :edit_app_configs # match
  resources :app_configs, only: %i[update] do
    collection do
      put :run_hourly_tasks
      put :run_daily_tasks
    end
  end

  get '/new_admin_user', to: 'application_setup#new_admin_user',
                         as: :new_admin_user
  post '/create_admin_user', to: 'application_setup#create_admin_user',
                             as: :create_admin_user
  resources :application_setup, only: %i[new_admin_user create_admin_user]

  get '/new_app_configs', to: 'application_setup#new_app_configs',
                          as: :new_app_configs
  post '/create_app_configs', to: 'application_setup#create_app_configs',
                              as: :create_app_configs
  put '/reload_catalog_cart', to: 'application#reload_catalog_cart',
                              as: :reload_cart
  delete '/empty_cart', to: 'application#empty_cart', as: :empty_cart

  get 'contact', to: 'contact#new', as: 'contact_us'
  post 'contact', to: 'contact#create', as: 'contact_submitted'

  get 'announcements/:id/hide',
      to: 'announcements#hide',
      as: 'hide_announcement'

  get 'status', to: 'status#index'

  get 'status/index'

  # this is a fix for running letter opener inside vagrant
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/catalog_controller.rb
# frozen_string_literal: true

# rubocop:disable ClassLength
class CatalogController < ApplicationController
  helper ReservationsHelper # for request_text
  layout 'application_with_sidebar'

  before_action :set_equipment_model, only:
    %i[add_to_cart remove_from_cart edit_cart_item]
  skip_before_action :authenticate_user!, unless: :guests_disabled?

  # --------- before filter methods --------- #

  def set_equipment_model
    @equipment_model = EquipmentModel.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    logger.error("Attempt to add invalid equipment model #{params[:id]}")
    flash[:notice] = 'Invalid equipment_model'
    redirect_to root_path
  end

  # --------- end before filter methods --------- #

  def index
    @reserver_id = session[:cart].reserver_id
    prepare_pagination
    prepare_catalog_index_vars
  end

  def add_to_cart
    change_cart(:add_item, @equipment_model)
  end

  def edit_cart_item
    change_cart(:edit_cart_item, @equipment_model, params[:quantity].to_i)
  end

  def update_user_per_cat_page
    if params[:items_per_page].present?
      session[:items_per_page] = params[:items_per_page]
    end
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render action: 'cat_pagination' }
    end
  end

  # this method updates item quantities using the edit_reservation_form
  def submit_cart_updates_form # rubocop:disable MethodLength, AbcSize
    flash.clear
    quantity = params[:quantity].to_i
    id = params[:id].to_i
    equipment_model = EquipmentModel.find(id)
    cart.send(:edit_cart_item, equipment_model, quantity)
    @errors = cart.validate_all # update the errors
    respond_to do |format|
      format.html do
        if cart.items.empty?
          redirect_to root_path
        else
          redirect_to new_reservation_path
        end
      end
      format.js do
        if cart.items.empty?
          # redirects to catalog page
          render inline: "window.location = '#{root_path}'"
        else
          # to prepare for making reservation
          @reservation = Reservation.new(start_date: cart.start_date,
                                         due_date: cart.due_date,
                                         reserver_id: cart.reserver_id)
          render template: 'cart_js/reservation_form'
        end
      end
    end
  end

  # called to update the dates in cart and trigger errors
  def change_reservation_dates
    flash.clear
    update_cart
    @errors = cart.validate_all # update the errors
    respond_to do |format|
      format.html { redirect_to new_reservation_path }
      format.js do
        # to prepare for making reservation
        @reservation = Reservation.new(start_date: cart.start_date,
                                       due_date: cart.due_date,
                                       reserver_id: cart.reserver_id)
        render template: 'cart_js/reservation_form'
      end
    end
  end

  def search
    if params[:query].blank?
      redirect_to(root_path) && return
    else
      @equipment_model_results =
        EquipmentModel.active.catalog_search(params[:query])
      @category_results = Category.catalog_search(params[:query])
      @equipment_item_results =
        EquipmentItem.catalog_search(params[:query])
      prepare_catalog_index_vars(@equipment_model_results)
      render('search_results') && return
    end
  end

  def deactivate
    if params[:deactivation_cancelled]
      flash[:notice] = 'Deactivation cancelled.'
      redirect_to categories_path
    elsif params[:deactivation_confirmed]
      super
    else
      flash[:error] = 'Oops, something went wrong.'
      redirect_to categories_path
    end
  end

  private

  # this method is called to either add or remove an item from the cart
  # it takes either :add_item or :remove_item as an action variable and adds
  # or removes the equipment_model set from params{} in the before_action.
  # Finally, it renders the root page and runs the javascript to update the
  # cart (or displays the appropriate errors)
  def change_cart(action, item, quantity = nil)
    cart.send(action, item, quantity)
    @errors = cart.validate_all
    flash[:error] = @errors.join("\n")
    flash[:notice] = 'Cart updated.'

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js do
        # this isn't necessary for EM show page updates but not sure how to
        # check for catalog views since it's always in the catalog controller
        prepare_catalog_index_vars([item])
        @item = item
        render template: 'cart_js/update_cart'
      end
    end
  end

  def prepare_pagination
    array = []
    array << params[:items_per_page].to_i
    array << session[:items_per_page].to_i
    array << @app_configs.default_per_cat_page
    array << 10
    items_per_page = array.reject { |a| a.blank? || a.zero? }.first
    # assign items per page to the passed params, the default or 10
    # depending on if they exist or not
    @per_page_opts = [10, 20, 25, 30, 50].unshift(items_per_page).uniq
    session[:items_per_page] = items_per_page
  end
end

app/views/catalog/_catalog_listing.html.erb
<% eq_models_by_category.each do |category, equipment_models| %>
  <% unless equipment_models.nil? %>
    <h2 class="catalog">
      <%= link_to category.name, category_equipment_models_path(category) %>
    </h2>
    <div class="thumbnails row">
      <% equipment_models.each do |equipment_model| %>
        <div class="col-md-4">
          <%= render partial: 'catalog/equipment_model_div', locals: {
            equipment_model: equipment_model,
            availability_hash: availability_hash,
            available_string: available_string,
            qualifications_hash: qualifications_hash
          } %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/catalog/_equipment_model_div.html.erb
<div class="thumbnail">
  <%= link_to equipment_model do %>
    <% image_tag (equipment_model.photo.attached? ? equipment_model.photo.variant(resize_to_fill: [260, 180]) : 'no-image.gif') %>
  <% end %>
  <h4 class="equipment_title">
    <%= link_to equipment_model.name, equipment_model, class: 'equipment_title_link', rel: 'tooltip', title: equipment_model.name %>
  </h4>

  <hr class="special-hr"/>
    <div class="col-md-3 availability-num">
      <span id="availability_<%= equipment_model.id %>">
        <%= availability_hash[equipment_model.id] %>
      </span>
    </div>

    <p class="model_availability col-md-9">
      <%= available_string %>
    </p>

  <hr class="special-hr"/>
  <div class="caption_cat">
    <p class="equipment_descr">
      <%= markdown_to_plain_text(equipment_model.description) %><br/>
      <%= link_to 'More Info', equipment_model, class: 'more_info' %>
    </p>
  </div>

  <div class="add_to_cart_box" id="add_to_cart_<%= equipment_model.id %>">
    <% @restricted = equipment_model.model_restricted?(cart.reserver_id) %>
    <% if @restricted %>
      <%= button_tag 'Add to Cart', class: 'btn btn-default disabled add_to_cart_disabled'%>
      <%= link_to "#qualifications_modal", class: 'not-qualified-icon', rel: 'tooltip', title: 'Not Qualified (click for more info)', :"data-toggle" => 'modal' do %>
        <i class="fa fa-exclamation-triangle"></i>
      <% end %>
      <% elsif availability_hash[equipment_model.id] > 0 %>
      <%= link_to 'Add to Cart', add_to_cart_path(equipment_model), :method => :put, :remote => true, :class => "btn btn-default add_to_cart" %>
    <% else %>
      <%= button_tag 'Add to Cart', :class => "btn btn-default disabled add_to_cart_disabled"%>
    <% end %>
  </div>

  <% if @restricted %>
    <div id="qualifications_modal" class="modal fade">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Qualification Required</h4>
          </div>
          <div class="modal-body">
            <p><%= qualifications_hash[equipment_model.id] %></p>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
  <% end %>

</div>

app/views/catalog/_no_equipment.html.erb
<p>
  <h3>No equipment found.
    <% if can? :manage, EquipmentModel %>
      Try creating some
      <%= link_to "Equipment Models", new_equipment_model_path %>
      first!
    <% end %>
  </h3>
</p>

app/views/catalog/cat_pagination.js.erb
location.reload(true);

app/views/catalog/index.html.erb
<% title 'Catalog' %>

<div id="models_available">
  <% if @eq_models_by_category.empty? %>
    <%= render partial: 'no_equipment' %>
  <% else %>
    <div class="row">
      <div id="pagination_line" class="col-md-12">
        <%# for kaminari pagination %>
        <%= paginate @page_eq_models_by_category,
              params: { controller: 'catalog', action: 'index' } %>
        <%= form_tag update_user_per_cat_page_path,
              id: 'items_per_form', class: 'form-inline pull-right',
              remote: true, method: 'put' do %>
          <%= label_tag :items_per_page, 'Items per page:' %>
          <%= select_tag :items_per_page,
                options_for_select(@per_page_opts, session[:items_per_page]),
                class: 'autosubmitme form-control' %>
        <% end %>
      </div>
    </div>

    <div id="catalog_listing">
      <%= render partial: 'catalog_listing', locals: {
        eq_models_by_category: @eq_models_by_category,
        available_string:      @available_string,
        availability_hash:     @availability_hash,
        qualifications_hash:   @qualifications_hash
      } %>
    </div>
    <%= paginate @page_eq_models_by_category %>
  <% end %>
</div>

app/views/catalog/search_results.html.erb
<% title %-Search results for "#{params[:query]}"- %>

<% unless @category_results.empty? %>
  <div class="row">
    <div class="col-md-9">
      <h2>Category Results</h2>
    </div>
  </div>
  <div class="row">
    <% @category_results.each do |category| %>
      <div class="col-md-3">
        <div class="well">
          <h3 class="catalog">
            <%# print category name %>
            <%= link_to category.name, category_equipment_models_path(category) %>
          </h3>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<% unless @equipment_model_results.empty? %>
  <div class="row">
    <div class="col-md-9">
      <h2>Equipment Model Results</h2>
    </div>
  </div>
  <div class="thumbnails row">
    <% @equipment_model_results.each do |equipment_model| %>
      <div class="col-md-4">
        <%= render partial: 'equipment_model_div', locals: {
          equipment_model:     equipment_model,
          availability_hash:   @availability_hash,
          available_string:    @available_string,
          qualifications_hash: @qualifications_hash
        } %>
      </div>
    <% end %>
  </div>
<% end %>

<% unless @equipment_item_results.empty? %>
  <div class="row">
    <div class="col-md-9">
      <h2>Equipment Item Results</h2>
    </div>
  </div>

  <div class="row">
    <% @equipment_item_results.each do |equipment_item| %>
      <div class="col-md-4">
        <div class="well">
          <p>
            <strong>Model:</strong>
            <%= link_to equipment_item.equipment_model.name, equipment_model_path(equipment_item.equipment_model) %>
          </p>
          <p>
            <strong>Item:</strong>
            <%= equipment_item.name %> (<%= equipment_item.serial %>)
          </p>
          <p>
            <strong>Status:</strong>
            <% if equipment_item.available? %>
              <span class="label label-success eo-table">Available</span>
            <% else %>
              <span class="label label-danger eo-table">Not Available</span>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
  </div>

<% end %>