config/routes.rb
# frozen_string_literal: true

Reservations::Application.routes.draw do
  root to: 'catalog#index'

  # routes for Devise
  devise_scope :user do
    devise_for :users
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  ## Concerns
  concern :deactivatable do
    member do
      put :deactivate
      put :activate
    end
  end

  concern :calendarable do
    member { get :calendar }
  end

  resources :documents,
            :requirements

  resources :equipment_items, concerns: %i[deactivatable calendarable]

  resources :announcements, except: [:show]

  resources :categories, concerns: %i[deactivatable calendarable] do
    resources :equipment_models, concern: :calendarable
  end

  resources :equipment_models, concerns: %i[deactivatable calendarable] do
    collection do
      put 'update_catalog_cart'
      delete 'empty_cart'
    end
    resources :equipment_items, concerns: :calendarable
  end

  get 'equipment_objects', to: redirect('equipment_items')
  get 'equipment_objects/:id', to: redirect('equipment_items/%<id>')

  get '/import_users/import', to: 'import_users#import_page',
                              as: :csv_import_page
  post '/import_users/imported', to: 'import_users#import',
                                 as: :csv_imported

  get '/import_equipment/import', to: 'import_equipment#import_page',
                                  as: :equip_import_page
  post '/import_equipment/imported', to: 'import_equipment#import',
                                     as: :equip_imported

  resources :users, concerns: :calendarable do
    collection do
      post :find
      post :quick_new
      post :quick_create
    end
    member do
      put :ban
      put :unban
      delete :empty_cart
    end
    get :autocomplete_user_last_name, on: :collection
  end

  get '/catalog/search', to: 'catalog#search', as: :catalog_search
  get '/markdown_help', to: 'application#markdown_help', as: :markdown_help

  resources :reservations do
    member do
      get :send_receipt
      put :renew
      put :archive
    end
  end

  # reservations views
  get '/reservations/manage/:user_id', to: 'reservations#manage',
                                       as: :manage_reservations_for_user
  get '/reservations/current/:user_id', to: 'reservations#current',
                                        as: :current_reservations_for_user

  get '/reservations/review/:id', to: 'reservations#review',
                                  as: :review_request
  put '/reservations/approve/:id', to: 'reservations#approve_request',
                                   as: :approve_request
  put '/reservations/deny/:id', to: 'reservations#deny_request',
                                as: :deny_request

  # reservation checkout / check-in actions
  put '/reservations/checkout/:user_id', to: 'reservations#checkout',
                                         as: :checkout
  put '/reservations/check-in/:user_id', to: 'reservations#checkin',
                                         as: :checkin
  get '/blackouts/flash_message', to: 'blackouts#flash_message',
                                  as: :flash_message
  get '/blackouts/new_recurring', to: 'blackouts#new_recurring',
                                  as: :new_recurring_blackout

  put '/reservation/update_index_dates', to: 'reservations#update_index_dates',
                                         as: :update_index_dates
  put '/reservation/view_all_dates', to: 'reservations#view_all_dates',
                                     as: :view_all_dates

  resources :blackouts do
    collection do
      post :create_recurring
    end
    member do
      get :flash_message
      delete :destroy_recurring
    end
  end

  put '/catalog/update_view', to: 'catalog#update_user_per_cat_page',
                              as: :update_user_per_cat_page
  get '/catalog', to: 'catalog#index', as: :catalog
  put '/add_to_cart/:id', to: 'catalog#add_to_cart', as: :add_to_cart
  put '/remove_from_cart/:id', to: 'catalog#remove_from_cart',
                               as: :remove_from_cart
  put '/catalog/edit_cart_item/:id', to: 'catalog#edit_cart_item',
                                     as: :edit_cart_item
  post '/catalog/submit_cart_updates_form/:id',
       to: 'catalog#submit_cart_updates_form', as: :submit_cart_updates
  put '/catalog/reload_catalog_cart', to: 'catalog#reload_catalog_cart',
                                      as: :reload_catalog_cart
  put '/catalog/change_reservation_dates',
      to: 'catalog#change_reservation_dates',
      as: :change_reservations_dates
  delete '/catalog/empty_cart', to: 'catalog#empty_cart',
                                as: :catalog_empty_cart

  get '/reports/index', to: 'reports#index', as: :reports
  get '/reports/subreport/:class/:id', to: 'reports#subreport', as: :subreport
  put '/reports/update', to: 'reports#update_dates', as: :update_dates

  get '/terms_of_service', to: 'application#terms_of_service', as: :tos

  # yes, both of these are needed to override rails defaults of
  # /controller/:id/edit
  get '/app_configs/', to: 'app_configs#edit', as: :edit_app_configs # match
  resources :app_configs, only: %i[update] do
    collection do
      put :run_hourly_tasks
      put :run_daily_tasks
    end
  end

  get '/new_admin_user', to: 'application_setup#new_admin_user',
                         as: :new_admin_user
  post '/create_admin_user', to: 'application_setup#create_admin_user',
                             as: :create_admin_user
  resources :application_setup, only: %i[new_admin_user create_admin_user]

  get '/new_app_configs', to: 'application_setup#new_app_configs',
                          as: :new_app_configs
  post '/create_app_configs', to: 'application_setup#create_app_configs',
                              as: :create_app_configs
  put '/reload_catalog_cart', to: 'application#reload_catalog_cart',
                              as: :reload_cart
  delete '/empty_cart', to: 'application#empty_cart', as: :empty_cart

  get 'contact', to: 'contact#new', as: 'contact_us'
  post 'contact', to: 'contact#create', as: 'contact_submitted'

  get 'announcements/:id/hide',
      to: 'announcements#hide',
      as: 'hide_announcement'

  get 'status', to: 'status#index'

  get 'status/index'

  # this is a fix for running letter opener inside vagrant
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  include SoftDeletable
  include Searchable
  searchable_on(:name)

  has_many :equipment_models, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  validates :max_per_user, :max_checkout_length, :max_renewal_length,
            :max_renewal_times, :renewal_days_before_due, :sort_order,
            numericality: { allow_nil: true, integer_only: true,
                            greater_than_or_equal_to: 0 }

  nilify_blanks only: [:deleted_at]

  # table_name is needed to resolve ambiguity for certain queries with
  # 'includes'
  scope :active, ->() { where("#{table_name}.deleted_at is null") }

  def maximum_per_user
    max_per_user || Float::INFINITY
  end

  def maximum_renewal_length
    max_renewal_length || 0
  end

  def maximum_renewal_times
    max_renewal_times || Float::INFINITY
  end

  def maximum_renewal_days_before_due
    renewal_days_before_due || Float::INFINITY
  end

  def maximum_checkout_length
    max_checkout_length || Float::INFINITY
  end

  private

  # We only need to specify equipment_models here, all other associations will
  # cascade as those are destroyed.
  def associated_records
    equipment_models
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  load_and_authorize_resource
  decorates_assigned :category
  before_action :set_current_category,
                only: %i[show edit update destroy deactivate]

  include ActivationHelper
  include CsvExport
  include Calendarable

  # --------- before filter methods -------- #
  def set_current_category
    @category = Category.find(params[:id])
  end
  # --------- end before filter methods -------- #

  def index
    @categories = if params[:show_deleted]
                    Category.all
                  else
                    Category.active
                  end
    respond_to do |format|
      format.html
      format.zip { download_equipment_data }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.zip do
        models = @category.equipment_models
        items = EquipmentItem.where(equipment_model_id: models.all.map(&:id))
        download_equipment_data(cats: [@category], models: models, items: items)
      end
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Successfully created category.'
      redirect_to @category
    else
      flash[:error] = 'Oops! Something went wrong with creating the category.'
      render action: 'new'
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Successfully updated category.'
      redirect_to @category
    else
      render action: 'edit'
    end
  end

  def deactivate
    if params[:deactivation_cancelled]
      flash[:notice] = 'Deactivation cancelled.'
      redirect_to @category
    elsif params[:deactivation_confirmed]
      @category.equipment_models.each do |em|
        Reservation.for_eq_model(em.id).finalized.each do |r|
          r.archive(current_user, 'The category was deactivated.')
           .save(validate: false)
        end
      end
      super
    else
      flash[:error] = 'Oops, something went wrong.'
      redirect_to @category
    end
  end

  private

  def category_params
    params.require(:category)
          .permit(:name, :max_per_user, :max_checkout_length, :deleted_at,
                  :max_renewal_times, :max_renewal_length, :sort_order,
                  :renewal_days_before_due)
  end

  def generate_calendar_reservations
    # we need uniq because it otherwise includes overdue reservations in the
    # date range twice
    (Reservation.for_cat(@category.id).finalized.where.not(status: 'archived')
      .includes(:equipment_item, :equipment_model)
      .overlaps_with_date_range(@start_date, @end_date) + \
      Reservation.for_cat(@category.id)
        .includes(:equipment_item, :equipment_model).overdue).uniq
  end

  def generate_calendar_resource
    @category
  end

  def calendar_name_method
    :equipment_model
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for @category, :html => { :class => "form-horizontal" } do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :max_per_user, label: "Maximum per user", hint: "leave blank if unrestricted" %>
  <%= f.input :max_checkout_length, label: "Maximum checkout length", hint: "leave blank if unrestricted" %>
  <%= f.input :sort_order, :hint => "lowest at top" %>
  <%= f.input :deleted_at, label: "Inactive", :as => :deleted %>

  <strong>Default Renewal Options</strong>
  <%= f.input :max_renewal_times, label: 'Maximum number of times this item may be renewed', hint: 'Leave blank for unrestricted.' %>
  <%= f.input :max_renewal_length, label: 'Maximum time allotted for each renewal period', hint: 'Default is zero. Actual renewal period will depend on availability.' %>
  <%= f.input :renewal_days_before_due, label: 'How many days before the due date should the Renew button become available?', hint: 'Leave blank to give the option to renew at any time.' %>

  <%= f.error :base %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.button :submit, :cancel => categories_path %> 
    </div>
  </div>
<% end %>

app/views/categories/_table.html.erb
<table id="table_categories" class="datatable-wide table table-striped table-bordered">
  <thead>
  <tr>
    <th>Name</th>
    <th>Max Per User</th>
    <th>Max Checkout Length (days)</th>
    <th>Sort Order</th>
  <% if can? :manage, Category %>
    <th class="no_sort"> </th>
    <th class="no_sort"> </th>
  <% end %>
  </tr>
  </thead>
  <tbody>
  <% for category in categories %>
    <tr>
      <td><%= link_to category.name, category %></td>
      <td><%= category.maximum_per_user %></td>
      <td><%= category.maximum_checkout_length %></td>
      <td><%= category.sort_order %></td>
      <% if can? :manage, Category %>
       <td><%= link_to "Edit", edit_category_path(category), :class => 'btn btn-default' %></td>
       <td><%= category.decorate.make_deactivate_btn %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/categories/edit.html.erb
<% title "Edit Category" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @category %> |
  <%= link_to "View All", categories_path %>
</p>

app/views/categories/index.html.erb
<% title "Categories" %>

<table id="table_woo" class="datatable-wide table table-striped table-bordered">
  <thead>
  <tr>
    <th>Name</th>
    <th>Max Per User</th>
    <th>Max Checkout Length (days)</th>
    <th>Sort Order</th>
  <%# these blank TH's necessary for the sort function %>
  <% if can? :manage, Category %>
    <th class="no_sort"> </th>
    <th class="no_sort"> </th>
  <% end %>
  </tr>
  </thead>
  <tbody>
  <% for category in @categories %>
    <tr>
      <td><%= link_to category.name, category %></td>
      <td><%= intify category.max_per_user %></td>
      <td><%= intify category.max_checkout_length %></td>
      <td><%= category.sort_order %></td>
      <% if can? :manage, Category %>
       <td><%= link_to "Edit", edit_category_path(category), class:  "btn btn-default" %></td>
       <td><%= category.decorate.make_deactivate_btn %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<hr />

<% if can? :manage, Category %>
  <%= link_to "New Category", new_category_path, class:  "btn btn-primary" %>
  <%= link_to "Import Categories", equip_import_page_path, class:  "btn btn-default" %>
  <%= link_to "Export Equipment Data", categories_path(format: 'zip'), class:  "btn btn-default" %>
<% end %>
<% if params[:show_deleted] %>
  <%= link_to "Hide Old Categories from List", categories_path, class:  "btn btn-default" %>
<% else %>
  <%= link_to "Show Old Categories in List", categories_path(:show_deleted => true), class:  "btn btn-default" %>
<% end %>

app/views/categories/new.html.erb
<% title "Add New Category" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", categories_path %></p>

app/views/categories/show.html.erb
<% title "Category: #{@category.name}" %>

<div class="btn-group">
  <%= link_to "Add new #{@category.name.singularize} model".titleize, new_category_equipment_model_path(@category), class: 'btn btn-default' %>
</div>
<hr />

<p>
  <strong>Max Per User:</strong>
  <%= intify @category.max_per_user %>
</p>
<p>
  <strong>Max Checkout Length:</strong>
  <%= dayify @category.max_checkout_length %>
</p>
<p>
  <strong>Sort Order:</strong>
  <%= @category.sort_order %>
</p>
<p>
  <strong>Activated:</strong>
  <%= @category.deleted_at == nil %>
</p>

<% unless (@category.max_renewal_length.nil?) or (@category.max_renewal_times.nil?) %>
  <p>
    <strong>Default Maximum Renewal Period:</strong>
    <%= pluralize(@category.maximum_renewal_length, 'day') %>
  </p>
  <% unless @category.renewal_days_before_due.nil? %>
    <p>
      Items in this category are by default available for renewal <strong>
      <%= pluralize(@category.maximum_renewal_days_before_due, 'day') %>
      </strong> before the reservation due date.
    </p>
  <% else %>
    <p>
      By default, items in this category may be renewed <strong>at any time</strong>.
    </p>
  <% end %>
  <p>
    <strong>Default Maximum Renewals per Reservation:</strong>
    <%= intify @category.max_renewal_times %>
  </p>
<% else %>
  <p>
    <strong><em>By default, items in this category are not available for renewal.</em></strong>
  </p>
<% end %>

<% if can? :manage, Category %>
  <% @equipment_models = @category.equipment_models.active %>
  <h2>Models</h2><hr />
  <p id="equipment_models">
    <%= render 'equipment_models/table' %>
  </p>
  <hr>
  <%= link_to "#{@category.name} Reservations Calendar", calendar_category_path(@category), class: 'btn btn-default' %>
  <%= link_to "Edit Category", edit_category_path(@category), class: 'btn btn-default' %>
  <%= category.make_deactivate_btn %>
  <%= link_to "Export Category Data", category_path(@category, format: 'zip'), class: 'btn btn-default' %>
  <%= link_to "View All Categories", categories_path, class: 'btn btn-default' %>
<% end %>