config/routes.rb
# frozen_string_literal: true

Reservations::Application.routes.draw do
  root to: 'catalog#index'

  # routes for Devise
  devise_scope :user do
    devise_for :users
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  ## Concerns
  concern :deactivatable do
    member do
      put :deactivate
      put :activate
    end
  end

  concern :calendarable do
    member { get :calendar }
  end

  resources :documents,
            :requirements

  resources :equipment_items, concerns: %i[deactivatable calendarable]

  resources :announcements, except: [:show]

  resources :categories, concerns: %i[deactivatable calendarable] do
    resources :equipment_models, concern: :calendarable
  end

  resources :equipment_models, concerns: %i[deactivatable calendarable] do
    collection do
      put 'update_catalog_cart'
      delete 'empty_cart'
    end
    resources :equipment_items, concerns: :calendarable
  end

  get 'equipment_objects', to: redirect('equipment_items')
  get 'equipment_objects/:id', to: redirect('equipment_items/%<id>')

  get '/import_users/import', to: 'import_users#import_page',
                              as: :csv_import_page
  post '/import_users/imported', to: 'import_users#import',
                                 as: :csv_imported

  get '/import_equipment/import', to: 'import_equipment#import_page',
                                  as: :equip_import_page
  post '/import_equipment/imported', to: 'import_equipment#import',
                                     as: :equip_imported

  resources :users, concerns: :calendarable do
    collection do
      post :find
      post :quick_new
      post :quick_create
    end
    member do
      put :ban
      put :unban
      delete :empty_cart
    end
    get :autocomplete_user_last_name, on: :collection
  end

  get '/catalog/search', to: 'catalog#search', as: :catalog_search
  get '/markdown_help', to: 'application#markdown_help', as: :markdown_help

  resources :reservations do
    member do
      get :send_receipt
      put :renew
      put :archive
    end
  end

  # reservations views
  get '/reservations/manage/:user_id', to: 'reservations#manage',
                                       as: :manage_reservations_for_user
  get '/reservations/current/:user_id', to: 'reservations#current',
                                        as: :current_reservations_for_user

  get '/reservations/review/:id', to: 'reservations#review',
                                  as: :review_request
  put '/reservations/approve/:id', to: 'reservations#approve_request',
                                   as: :approve_request
  put '/reservations/deny/:id', to: 'reservations#deny_request',
                                as: :deny_request

  # reservation checkout / check-in actions
  put '/reservations/checkout/:user_id', to: 'reservations#checkout',
                                         as: :checkout
  put '/reservations/check-in/:user_id', to: 'reservations#checkin',
                                         as: :checkin
  get '/blackouts/flash_message', to: 'blackouts#flash_message',
                                  as: :flash_message
  get '/blackouts/new_recurring', to: 'blackouts#new_recurring',
                                  as: :new_recurring_blackout

  put '/reservation/update_index_dates', to: 'reservations#update_index_dates',
                                         as: :update_index_dates
  put '/reservation/view_all_dates', to: 'reservations#view_all_dates',
                                     as: :view_all_dates

  resources :blackouts do
    collection do
      post :create_recurring
    end
    member do
      get :flash_message
      delete :destroy_recurring
    end
  end

  put '/catalog/update_view', to: 'catalog#update_user_per_cat_page',
                              as: :update_user_per_cat_page
  get '/catalog', to: 'catalog#index', as: :catalog
  put '/add_to_cart/:id', to: 'catalog#add_to_cart', as: :add_to_cart
  put '/remove_from_cart/:id', to: 'catalog#remove_from_cart',
                               as: :remove_from_cart
  put '/catalog/edit_cart_item/:id', to: 'catalog#edit_cart_item',
                                     as: :edit_cart_item
  post '/catalog/submit_cart_updates_form/:id',
       to: 'catalog#submit_cart_updates_form', as: :submit_cart_updates
  put '/catalog/reload_catalog_cart', to: 'catalog#reload_catalog_cart',
                                      as: :reload_catalog_cart
  put '/catalog/change_reservation_dates',
      to: 'catalog#change_reservation_dates',
      as: :change_reservations_dates
  delete '/catalog/empty_cart', to: 'catalog#empty_cart',
                                as: :catalog_empty_cart

  get '/reports/index', to: 'reports#index', as: :reports
  get '/reports/subreport/:class/:id', to: 'reports#subreport', as: :subreport
  put '/reports/update', to: 'reports#update_dates', as: :update_dates

  get '/terms_of_service', to: 'application#terms_of_service', as: :tos

  # yes, both of these are needed to override rails defaults of
  # /controller/:id/edit
  get '/app_configs/', to: 'app_configs#edit', as: :edit_app_configs # match
  resources :app_configs, only: %i[update] do
    collection do
      put :run_hourly_tasks
      put :run_daily_tasks
    end
  end

  get '/new_admin_user', to: 'application_setup#new_admin_user',
                         as: :new_admin_user
  post '/create_admin_user', to: 'application_setup#create_admin_user',
                             as: :create_admin_user
  resources :application_setup, only: %i[new_admin_user create_admin_user]

  get '/new_app_configs', to: 'application_setup#new_app_configs',
                          as: :new_app_configs
  post '/create_app_configs', to: 'application_setup#create_app_configs',
                              as: :create_app_configs
  put '/reload_catalog_cart', to: 'application#reload_catalog_cart',
                              as: :reload_cart
  delete '/empty_cart', to: 'application#empty_cart', as: :empty_cart

  get 'contact', to: 'contact#new', as: 'contact_us'
  post 'contact', to: 'contact#create', as: 'contact_submitted'

  get 'announcements/:id/hide',
      to: 'announcements#hide',
      as: 'hide_announcement'

  get 'status', to: 'status#index'

  get 'status/index'

  # this is a fix for running letter opener inside vagrant
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/equipment_models_controller.rb
# frozen_string_literal: true

# rubocop:disable ClassLength
class EquipmentModelsController < ApplicationController
  layout 'application_with_sidebar', only: :show
  load_and_authorize_resource
  decorates_assigned :equipment_model
  skip_before_action :authenticate_user!, only: %i[show index],
                                          unless: :guests_disabled?
  before_action :set_equipment_model,
                only: %i[show edit update destroy deactivate]
  before_action :set_category_if_possible, only: %i[index new]

  include ActivationHelper
  include CsvExport
  include Calendarable

  # --------- before filter methods --------- #
  def set_equipment_model
    @equipment_model = EquipmentModel.find(params[:id])
  end

  def set_category_if_possible
    @category = Category.find(params[:category_id]) if params[:category_id]
  end
  # --------- end before filter methods --------- #

  def index
    base = @category ? @category.equipment_models : EquipmentModel.all
    if params[:show_deleted]
      @equipment_models = base.includes(:reservations)
    else
      @equipment_models = base.includes(:reservations).active
    end

    respond_to do |format|
      format.html
      format.zip { download_equipment_data }
    end
  end

  def show # rubocop:disable AbcSize, MethodLength
    calculate_availability
    relevant_reservations =
      Reservation.for_eq_model(@equipment_model.id).active
    @associated_equipment_models =
      @equipment_model.associated_equipment_models.sample(6)

    calendar_length = 1.month

    @reservation_data = relevant_reservations.collect do |r|
      end_date = if r.overdue
                   Time.zone.today + calendar_length
                 else
                   r.due_date
                 end
      { start: r.start_date, end: end_date }
      # the above code mimics the current available? setup to show overdue
      # equipment as permanently 'out'.
    end

    @blackouts = Blackout.active.collect do |b|
      { start: b.start_date, end: b.end_date }
    end

    @date = Time.zone.today
    @date_max = @date + calendar_length - 1.week
    @max = @equipment_model.equipment_items.active.count

    @restricted = @equipment_model.model_restricted?(cart.reserver_id)

    # For pending reservations table
    @pending =
      relevant_reservations.reserved
                           .overlaps_with_date_range(Time.zone.today,
                                                     Time.zone.today + 8.days)
    # Future reservations using Query object
    @future = @pending.future
  end

  def new
    @equipment_model = EquipmentModel.new(category: @category)
  end

  def create
    @equipment_model = EquipmentModel.new(equipment_model_params)
    if @equipment_model.save
      flash[:notice] = 'Successfully created equipment model.'
      redirect_to @equipment_model
    else
      flash[:error] = 'Please review the errors below. '
      render action: 'new'
    end
  end

  def edit; end

  def update
    delete_files

    eq_params = equipment_model_params

    if @equipment_model.update(eq_params)
      # hard-delete any deleted checkin/checkout procedures
      delete_procedures(params, 'checkout')
      delete_procedures(params, 'checkin')
      flash[:notice] = 'Successfully updated equipment model.'
      redirect_to @equipment_model
    else
      render action: 'edit'
    end
  end

  def deactivate
    if params[:deactivation_cancelled]
      flash[:notice] = 'Deactivation cancelled.'
      redirect_to @equipment_model
    elsif params[:deactivation_confirmed]
      Reservation.for_eq_model(@equipment_model.id).finalized.each do |r|
        r.archive(current_user, 'The equipment model was deactivated.')
         .save(validate: false)
      end
      super
    else
      flash[:error] = 'Oops, something went wrong.'
      redirect_to @equipment_model
    end
  end

  private

  # function to check for deleted checkin/checkout procedures and hard-delete
  # them after equipment model update
  def delete_procedures(params, phase)
    # phase needs to be equal to either "checkout" or "checkin"
    phase_params = params[:equipment_model][:"#{phase}_procedures_attributes"]
    return if phase_params.nil?
    phase_params.each do |k, v|
      if v['id'] && v['_destroy'] != 'false'
        @equipment_model.send(:"#{phase}_procedures")[k.to_i].destroy(:force)
      end
    end
  end

  def delete_files
    # for a given filetype affected by param value, the file in question is
    # saved in path contained value
    types = { 'clear_documentation' => :documentation,
              'clear_photo' => :photo }

    # only keep pairs that occur as keys with non-nil values in params
    types.select! { |k, v| params.keys.member?(k) && !v.nil? }
    types.each { |_k, attr| params[:equipment_model][attr] = nil }
  end

  def equipment_model_params
    # manually add on the procedure elements from params since they
    # don't have fixed hash keys (check to see if they exist first
    # to resolve test failures)
    params.require(:equipment_model)
          .permit(:name, :category_id, :category, :description, :late_fee,
                  :replacement_fee, :max_per_user, :deleted_at, :photo,
                  :documentation, :max_renewal_times, :max_renewal_length,
                  :renewal_days_before_due, :late_fee_max,
                  { associated_equipment_model_ids: [] }, :requirement_ids,
                  :requirements, :max_checkout_length,
                  checkin_procedures_attributes: {},
                  checkout_procedures_attributes: {})
  end

  def generate_calendar_reservations
    # we need uniq because it otherwise includes overdue reservations in the
    # date range twice
    (Reservation.for_eq_model(@equipment_model.id).includes(:equipment_item)
      .overlaps_with_date_range(@start_date, @end_date).finalized
      .where.not(status: 'archived') + \
      Reservation.for_eq_model(@equipment_model.id).includes(:equipment_item)
        .overdue).uniq
  end

  def generate_calendar_resource
    @equipment_model
  end

  def calendar_name_method
    :reserver
  end

  def calculate_availability
    # get start and end dates
    @start_date = Time.zone.today.beginning_of_week(:sunday)
    @end_date = (Time.zone.today + 1.month).end_of_week(:sunday)

    max_avail = @equipment_model.equipment_items.active.count

    @avail_data = []
    (@start_date..@end_date).map do |date|
      availability = @equipment_model.num_available_on(date)
      # set up colors
      if date < Time.zone.today
        color = '#888'
      elsif availability.zero?
        color = '#d9534f'
      elsif availability == max_avail
        color = '#5cb85c'
      elsif availability > [0.25 * max_avail, 1].max
        color = '#94d194'
      elsif availability <= [0.25 * max_avail, 1].max
        color = '#f0ad4e'
      end
      @avail_data << { title: availability.to_s, start: date, end: date,
                       allDay: true, color: color }
    end
  end
end

app/helpers/equipment_models_helper.rb
# frozen_string_literal: true

module EquipmentModelsHelper
  def evaluate_img_presence(equipment_model)
    if equipment_model.photo.attached?
      equipment_model.photo.variant(resize_to_fill: [150, 150])
    else
      'no-image-260.gif'
    end
  end

  def available_item_select_options(em)
    items = em.equipment_items.active.select(&:available?).sort_by(&:name)
    items.collect do |item|
      "<option value=#{sanitize item.id.to_s}>"\
        "#{sanitize item.name}</option>"
    end.join
  end
end

app/views/equipment_models/_add_to_cart.html.erb
<% if @equipment_model.deleted_at %>
  <%= button_tag "Deactivated", remote: true, class: 'btn btn-danger btn-large disabled' %>
<% elsif @restricted %>
  <%= link_to "#qualifications_modal",
    class: '',
    rel: "tooltip",
    title: 'Not Qualified (click for more info)',
    :"data-toggle" => 'modal' do %>
    <%= button_tag "Not Qualified", remote: true, class: 'btn btn-warning btn-large' %>
  <% end %>
   <div id="qualifications_modal" class="modal fade">
     <div class="modal-dialog">
       <div class="modal-content">
         <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h4 class="modal-title"><%= "Qualification Required" %></h4>
         </div>
         <div class="modal-body">
           <p>
             <%= list_requirement_admins(current_user, @equipment_model) %>
           </p>
        </div>
       </div>
     </div>
  </div>
 <% else %>
   <%= link_to "Add to Cart", {:url => add_to_cart_path(@equipment_model)},
                               :href => add_to_cart_path(@equipment_model),
                               :method => :put, :remote => true, :class => 'btn btn-primary btn-large' %>
 <% end %>

app/views/equipment_models/_calendar.html.erb
<h4>Availability</h4>

<div id="avail-cal" data-src="<%= @avail_data.to_json %>" data-min="<%= @start_date %>" data-max="<%= @end_date %>"></div>

app/views/equipment_models/_checkin_procedure_fields.html.erb
<div class="checkin_procedure nested-fields">
<%= f.input :step, :wrapper => :horizontal_input_group do %>
  <%= f.input_field :step, class: 'form-control' %>
  <div class="input-group-btn">
    <%= link_to_remove_association "Remove Step", f, :class => "btn btn-default" %>
  </div>
<% end %>
</div>

app/views/equipment_models/_checkout_procedure_fields.html.erb
<div class="checkout_procedure, nested-fields">
  <%= f.input :step, :wrapper => :horizontal_input_group do %>
    <%= f.input_field :step, class: 'form-control' %>
    <span class="input-group-btn">
      <%= link_to_remove_association "Remove Step", f, :class => "btn btn-default" %>
    </span>
  <% end %>
</div>

app/views/equipment_models/_equipment_items_table.html.erb
<table id="table_woo" class="datatable table table-striped table-bordered">
  <thead>
  <tr>
    <th>Name</th>
    <th>Serial</th>
    <th>Status</th>
<%# these blank TH's necessary for the sort function %>
  <% if can? :manage, EquipmentItem %>
    <th class="no_sort"> </th>
    <th class="no_sort"> </th>
  <% end %>
  </tr>
  </thead>
  <tbody>
  <% for equipment_item in @equipment_model.equipment_items %>
    <tr>
      <td><%= link_to equipment_item.name, equipment_item %></td>
      <td><%= equipment_item.serial %></td>
      <% if equipment_item.status == 'available' %>
        <td><span class="label label-success eo-table">Available</span></td>
      <% else %>
        <% current_res = equipment_item.current_reservation %>
        <td><%= link_to_if current_res, equipment_item.status, current_res %></td>
      <% end %>
      <% if can? :manage, EquipmentItem %>
        <td><%= link_to 'Edit', edit_equipment_item_path(equipment_item), class: 'btn btn-default' %></td>
        <td><%= equipment_item.decorate.make_deactivate_btn %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/equipment_models/_form.html.erb
<%= simple_form_for @equipment_model, html: { multipart: true, class:
  "form-horizontal" } do |f| %>

  <%= f.error_notification %>
  <%= f.association :category, wrapper: :horizontal_select2, hint: "#{link_to "Add New Category", new_category_path, class: "btn btn-default"}".html_safe,
  placeholder: 'Select a Category' %>

  <input class="hidden" id="category" name="MODELNAME[category]" type="hidden">

  <%= f.association :associated_equipment_models, wrapper: :horizontal_select2,
  input_html: {class: 'input-xlarge'},
  placeholder: 'Start typing an equipment model name', collection:
  EquipmentModel.where("id != ?", params[:id]) %>

  <%# TODO: review this. do we want it here? %>
  <%#= f.association :requirements, input_html: {class: 'input-xlarge select2-input select2-focused', id:'requirement_equipment_model'},
  placeholder: 'Start typing an equipment model name', collection: Requirement.all.map{|req| [req.description,req.id]} %>

  <%= f.input :name %>

  <%= f.input :description, as: :text,
  hint: "#{render :partial => 'shared/markdown_button'}".html_safe,
  input_html: { rows: 10 } %>

  <%= f.input :late_fee, wrapper: :horizontal_input_group, required: true do %>
    <%= content_tag :span, "$", class: "input-group-addon" %>
    <%= f.input_field :late_fee,
      class: 'form-control', value: number_with_precision(f.object.late_fee,
      precision: 2), type: 'number', step: 'any' %>
  <% end %>

  <%= f.input :replacement_fee, wrapper: :horizontal_input_group, required: true do %>
    <%= content_tag :span, "$", class: "input-group-addon" %>
    <%= f.input_field :replacement_fee,
      class: 'form-control', value: number_with_precision(f.object.replacement_fee,
      precision: 2), type: 'number', step: 'any' %>
  <% end %>

  <%= f.input :late_fee_max, wrapper: :horizontal_input_group, hint: 'Maximum possible late fee (set to zero for unlimited).' do %>
    <%= content_tag :span, "$", class: "input-group-addon" %>
    <%= f.input_field :late_fee_max,
      class: 'form-control', value: number_with_precision(f.object.late_fee_max,
      precision: 2), type: 'number', step: 'any' %>
  <% end %>

  <%= f.input :max_per_user, label: "Maximum per user", hint:
  "Leave blank to default to category value." %>

  <%= f.input :deleted_at, label: "Inactive", as: :deleted, hint:
  'Make this equipment model unavailable for checkout.' %>

  <%= f.input :max_checkout_length, label: 'Maximum time alloted for each checkout period',
    hint: 'Leave blank to default to category value.' %>

    <fieldset>
    <legend>Renewal Options</legend>
    <%= f.input :max_renewal_times, label: 'Maximum number of times this item may be renewed',
    hint: 'Leave blank to default to category value.', wrapper: :horizontal_input_group do %>
      <%= f.input_field :max_renewal_times, class: 'form-control', type: 'number' %><%=
      content_tag :span, "times", class: "input-group-addon" %>
    <% end %>

    <%= f.input :max_renewal_length, label: 'Maximum time allotted for each renewal period',
    hint: 'Leave blank to default to category value. Actual renewal period will depend on availability.',
    wrapper: :horizontal_input_group do %>
      <%= f.input_field :max_renewal_length, class: 'form-control', type: 'number' %><%=
      content_tag :span, "days", class: "input-group-addon" %>
    <% end %>

    <%= f.input :renewal_days_before_due, label:
    'How many days before the due date should the Renew button become available?',
    hint: 'Leave blank to default to category value.', wrapper: :horizontal_input_group do %>
      <%= f.input_field :renewal_days_before_due, class: 'form-control', type: 'number' %><%=
      content_tag :span, "days", class: "input-group-addon" %>
    <% end %>
  </fieldset>

  <fieldset>
    <p><legend>Checkout Procedures</legend></p>
    <%= f.simple_fields_for :checkout_procedures do |procedure| %>
      <%= render 'checkout_procedure_fields', f: procedure %>
    <% end %>
    <div class="links">
      <p><%= link_to_add_association 'Add Step', f, :checkout_procedures,
      class: "btn btn-default" %></p>
    </div>
  </fieldset>

  <fieldset>
    <p><legend>Checkin Procedures</legend></p>
    <%= f.simple_fields_for :checkin_procedures, wrapper: :horizontal_input_group do |procedure| %>
      <%= render 'checkin_procedure_fields', f: procedure %>
    <% end %>
    <div class="links">
      <p><%= link_to_add_association 'Add Step', f, :checkin_procedures,
      class: "btn btn-default" %></p>
    </div>
  </fieldset>

  <fieldset>
    <legend>Media</legend>
    
    <div class="form-field">
      <%= f.label :photo, "Upload photo" %>
      <%= f.file_field :photo,
          accept: 'image/jpg,image/png,image/jpeg',
          direct_upload: true %>
    </div>

    <% if @equipment_model.photo.attached? %>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-7">

          <%= image_tag @equipment_model.photo.variant(resize_to_fill: [260, 180]) %>
          <%= label_tag :clear_photo do %>
            <%= check_box_tag :clear_photo, nil, false %>
            Delete current photo?
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="form-field">
      <%= f.label :documentation, "Upload Documentation" %>
      <%= f.file_field :documentation,
          accept: 'application/pdf',
          direct_upload: true %>
    </div>

    <% if @equipment_model.documentation.attached? %>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-7">
          <% if !@equipment_model.documentation_blob.nil? %>
            <h4>
              <%= (link_to @equipment_model.documentation_blob.filename,
                   rails_blob_url(@equipment_model.documentation), target: "_blank") %>
            </h4>
          <% end %>
          <%= label_tag :clear_documentation do %>
            <%= check_box_tag :clear_documentation, nil, false %>
            Delete current documentation?
          <% end %>
        </div>
      </div>
    <% end %>
  </fieldset>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.button :submit, cancel: equipment_models_path %>
    </div>
  </div>
<% end %>

app/views/equipment_models/_pending_reservations_table.erb
<table id="pending_reservations_table" class="datatable table table-striped table-bordered">
  <thead>
  <tr>
    <th>ID</th>
    <th>Reserver</th>
    <th>Start Date</th>
    <th>Due Date</th>
  </tr>
  </thead>
  <tbody>
  <% for reservation in (@pending) %>
    <tr>
      <td><%= link_to reservation.id, reservation %></td>
      <td><%= link_to reservation.reserver.name, reservation.reserver %></td>
      <td><%= reservation.start_date.to_date %></td>
      <td><%= reservation.due_date.to_date %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/equipment_models/_table.html.erb
<table id="table_equipment_models" class="datatable-wide table table-striped table-bordered">
  <thead>
  <tr>
    <th class="text-center col-md-2">Name</th>
    <% if can? :view_detailed, EquipmentModel %>
      <th class="no_sort text-center">Current Status</th>
      <th class="text-center">Available</th>
      <th class="text-center">Reserved</th>
      <th class="text-center">Checked-Out</th>
      <th class="text-center">Overdue</th>
      <th class="text-center">Total Stock</th>
      <% if can? :manage, EquipmentModel %>
        <th class="no_sort text-center"> </th>
        <th class="no_sort text-center"> </th>
      <% end%>
    <% end %>
  </tr>
  </thead>
  <tbody>
    <% for equipment_model in @equipment_models %>
    <tr>
      <td class="text-center"><%= link_to equipment_model.name, equipment_model %></td>
      <% if can? :view_detailed, EquipmentModel %>
        <% if equipment_model.availability(Time.zone.today) == 'all' %>
          <td class="text-center"><span class="label label-success">All  Available</span></td>
        <% elsif equipment_model.availability(Time.zone.today) == 'some' %>
          <td class="text-center"><span class="label label-warning">Some Available</span></td>
        <% else %>
          <td class="text-center"><span class="label label-danger">None Available</span></td>
        <% end %>
        <td class="text-center"><%= equipment_model.num_available_on(Time.zone.today) %></td>
        <td class="text-center"><%= equipment_model.num_busy(Time.zone.today, Time.zone.today, equipment_model.reservations)%></td>
        <td class="text-center"><%= equipment_model.reservations.checked_out.count %></td>
        <td class="text-center"><%= equipment_model.overdue_count %></td>
        <td class="text-center"><%= equipment_model.equipment_items.count %></td>
        <% if can? :manage, EquipmentModel %>
          <td class="text-center"><%= link_to "Edit", edit_equipment_model_path(equipment_model), class: "btn btn-default" %></td>
          <td class="text-center"><%= equipment_model.decorate.make_deactivate_btn %></td>
        <% end%>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/equipment_models/edit.html.erb
<% title "Edit Equipment Model" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @equipment_model %> |
  <%= link_to "View All", equipment_models_path %>
</p>

app/views/equipment_models/index.html.erb
<% title (@category.blank? ? "Equipment Models" : @category.name.pluralize) %>

<%= render 'table' %>

<hr>
<% if can? :manage, EquipmentModel %>
  <% if @category %>
    <%= link_to "New #{@category.name.singularize}", new_category_equipment_model_path(@category), class:  'btn btn-primary' %>
    <%= link_to "#{@category.name} Reservations Calendar", calendar_category_path(@category), class: 'btn btn-default' %>
    <%= link_to "View All Equipment Models", equipment_models_path, class:  'btn btn-default' %>
    <%= link_to "Import Equipment Models", equip_import_page_path, class:  "btn btn-default" %>
    <%= link_to "Export Equipment Data", category_path(@category, format: 'zip'), class:  "btn btn-default" %>
  <% else %>
    <%= link_to "New Equipment Model", new_equipment_model_path, class:  "btn btn-primary" %>
    <%= link_to "Import Equipment Models", equip_import_page_path, class:  "btn btn-default" %>
    <%= link_to "Export Equipment Data", equipment_models_path(format: 'zip'), class:  "btn btn-default" %>
  <% end %>
  <% if params[:show_deleted] %>
    <% if (@category.nil?) %>
      <%= link_to "Hide Deactivated Models", equipment_models_path, class:  "btn btn-default" %>
    <% else %>
      <%= link_to "Hide Deactivated Models", category_equipment_models_path(@category), class:  "btn btn-default" %>
    <% end %>
  <% else %>
    <% if (@category.nil?) %>
      <%= link_to "Show Deactivated Models", equipment_models_path(show_deleted: true), class:  "btn btn-default" %>
    <% else %>
      <%= link_to "Show Deactivated Models", category_equipment_models_path(@category, show_deleted: true), class:  "btn btn-default" %>
    <% end %>
  <% end %>
<% else %>
  <%= link_to "Return to Catalog", catalog_path, class:  'btn btn-default' %>
<% end %>

app/views/equipment_models/new.html.erb
<% title "Add New " + (@category.nil? ? "Equipment Model" : @category.name.singularize) %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", (@category.nil? ? equipment_models_path : category_equipment_models_path(@category)) %></p>